print("hola mi nombre es windows 10 ")
nombre=input("y cual es tu nombre: ")
nombre=print("Hola: " + nombre)
lugar=input("donde vives: ")
lugar=print("vives:" + lugar )
años= input("cuantos años tiene:")
años= print("tienes:" + años)
print("que te parece si hacemos una suma")
valor1=input("ingresa el primer valor: ")
valor2=input("ingresa el segundo valor:")
resultado=print( int(valor1)+ int(valor2) )
nombre=print("Muy bien")
print("que te parece si hacemos una resta")
valor3=input("ingresa el primer valor:")
valor4=input("ingresa el segundo valor:")
resultado2=print( int(valor3)- int(valor4))
print("que te parece si hacemos un multiplicacion") 
valor5=input("ingresa el primer valor:")
valor6=input("ingresa el segundo valor:")
resultado3=print( int(valor5) * int(valor6))
print("que te parece si hacemos una division") 
valor7=input("ingresa el primer valor:")
valor8=input("ingresa el segundo valor:")
resultado3=print( int(valor7) / int(valor8))
print("muy bien has terminado las operaciones con exito")
